"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file at the project root.
load_dotenv(BASE_DIR / '.env')

def env(name, default=None):
    """Read a setting from the environment, treating blank as unset."""
    value = os.getenv(name)
    return value if value not in (None, "") else default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&mdjvwv!&yo0=j&lc^17gm@y*a=#hg17%5-3f91o^05&0e^&0r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',

    'apps.authentication',
    'apps.user',
    'apps.core',
    'apps.landing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#     },
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # ScopedRateThrottle only acts on views that declare a throttle_scope, so
    # listing it as a default throttles the auth endpoints and leaves the rest
    # alone. Rates are per client IP for anonymous callers.
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.ScopedRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     # Entering a 6-digit code. This is the one that matters: without it the
    #     # whole code space is walkable in minutes.
    #     'auth_code_entry': '10/hour',
    #     # Anything that sends mail - also what stops the API being used as a
    #     # spam relay against a third party's inbox.
    #     'auth_email_send': '5/hour',
    #     'auth_login': '20/hour',
    # },
}

# Throttle counters live in the cache, so the default per-process LocMemCache
# means each worker enforces its own limit. Point this at Redis or Memcached
# before running more than one process.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'auth-throttle',
    }
}

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'user.User'

# Whether to believe X-Forwarded-For when recording a login attempt's IP.
# Leave False unless a proxy you control actually sets it: a client can send the
# header itself, so trusting it while directly exposed lets an attacker spread a
# brute-force across invented addresses and poison the audit trail.
TRUSTED_PROXY_HEADER = False

# Require users to verify their email address before they can log in.
# When False, verification emails are still sent but login is not gated.
REQUIRE_EMAIL_VERIFICATION = False

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# 465/implicit-SSL rather than 587/STARTTLS: ISPs commonly block outbound 25 and
# 587, and a blocked port surfaces here as a registration 503 (the verification
# email is what RegisterView's atomic block hangs on). TLS and SSL are mutually
# exclusive in Django, so the two flags come off one switch.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(env('EMAIL_PORT', '465'))
EMAIL_USE_SSL = env('EMAIL_USE_SSL', 'True') == 'True'
EMAIL_USE_TLS = not EMAIL_USE_SSL
EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')
# Without this a blocked port stalls the request for the OS default (~75s)
# before the 503 comes back.
EMAIL_TIMEOUT = 15
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', f'Auth<{EMAIL_HOST_USER}>')

# Brand name shown in the email templates (header, greeting, footer).
APP_NAME = env('APP_NAME', 'Auth')

# OpenAPI schema, served at /api/schema/ with Swagger UI and ReDoc over it.
#
# The views are plain APIViews over plain Serializers, so nothing here is
# inferred - every endpoint carries an explicit @extend_schema in views.py, and
# `python manage.py spectacular --fail-on-warn` is what keeps it that way.
SPECTACULAR_SETTINGS = {
    'TITLE': f'{APP_NAME} Authentication API',
    'DESCRIPTION': (
        'Email-and-password authentication: registration, 6-digit email '
        'verification, token login, password reset and password change.\n\n'
        'Authenticated requests carry the DRF token as '
        '`Authorization: Token <key>`.'
    ),
    'VERSION': '1.0.0',
    # The schema endpoint serves the UIs; it shouldn't also document itself.
    'SERVE_INCLUDE_SCHEMA': False,
    # REST_FRAMEWORK's DEFAULT_PERMISSION_CLASSES is IsAuthenticated, so say out
    # loud that the docs are public rather than leaning on the library default.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# Without this, the traceback logged when an email fails and its writes are
# rolled back goes nowhere.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'apps.authentication': {'handlers': ['console'], 'level': 'INFO'},
    },
}